### ISSUE TITLE
[100] Merge our product in Tribler

### ISSUE THREAD

**Issue by MaxVanDeursen** [vandenheuvel/tribler#159]
In order to merge this complete feature into  the actual Tribler repository, the following things have to be done:

- [x] #161 Adjust Linux builder dependencies
- [x] #162 Adjust Mac builder dependencies
- [x] #165 Adjust Mac builder
- [x] https://github.com/vandenheuvel/tribler/issues/248 Windows 32-bit testing
- [x] https://github.com/vandenheuvel/tribler/issues/250 Windows 64-bit testing
- [x] #168 Adjust GUI tests
- [x] https://github.com/vandenheuvel/tribler/issues/175 Incorporate feedback
- [x] https://github.com/vandenheuvel/tribler/issues/312 Complete this checklist

The pull request has already been opened: https://github.com/Tribler/tribler/pull/2958
