### ISSUE TITLE
[100] Product vision (max. 8 pages A4)

### ISSUE THREAD

**Issue by rkeulemans** [vandenheuvel/tribler#20]
"This document must be created by answering the following fundamental questions [1]:

- [x] #25 Who is going to buy the product? Who is the target customer? - 3

- [x] #26 Which customer needs will the product address? - 5
- [x] #27 Which product attributes are crucial to satisfy the selected needs, and therefore to the success of the product? - 5
- [x] #28 How does the product compare against existing products, both from competitors and the same company? What are the product’s unique selling points? - 3
- [x] #29 What is the target timeframe and budget to develop and launch the product? - 4
- [ ] Readying for hand in
Each of the questions will lead to a corresponding section of the document. For background information and detailed instructions on how to write each section, please consult

[1] Roman Pichler, Product Vision, http://www.scrumalliance.org/community/articles/2009/january/the-product-vision

NOTE: Answering these questions requires a literature study and analysis of the existing alternatives to the envisioned realization of the target software product. The corresponding section of this deliverable will provide input for the grade of the Information Skills course (see Section 8 for assessment process and criteria)."

Above info is a copy from: https://docs.google.com/document/d/19J8In7yXjVMQPCNsysOrMUZcK1h6n60V37eOJP-xMWE/pub

Read only link to this document: https://www.overleaf.com/read/dsqqncqtcfkj
