### ISSUE TITLE
[13] Get information from the network using a crawler

### ISSUE THREAD

**Issue by ghabbenjansen** [vandenheuvel/tribler#206]
As a user, I want to see the network further than only my direct neighbors.

- [x] Find out how the crawler in Tribler works (#208)
- [x] Integrate the crawler into the visualisation (#210)
- [x] Ensure that the crawled data are displayed correctly (#212)
