### ISSUE TITLE
[100] Product planning (max. 6 pages A4)

### ISSUE THREAD

**Issue by rkeulemans** [vandenheuvel/tribler#21]
"This document will be created according to the following Table of Contents (TOC):

- [x] #30 Introduction - 4
- [x] #31 Product - 5
    - High-level product backlog (set of epics aligned with the product vision)
    - Roadmap (major release schedule, release goals)
- [x] #32 Product backlog (first version with estimates and prioritized user stories) - 5
    - User stories of features
    - User stories of defects (if applicable)
    - User stories of technical improvements (if applicable)
    - User stories of know-how acquisition
    - Initial release plan (milestones, MRFs per release)
- [x] #33 Definition of Done (backlog items, sprints, releases) - 5
- [x] #30 Glossary - 1
- [x] Readying for hand in

For an overview of what the document should contain, consult Kenneth S. Rubin, “Essential Scrum: A Practical Guide to the Most Popular Agile Process” (login first at http://proquest.safaribooksonline.com/), in particular chapters 15 and 17. An example document will be posted on Blackboard."

This is a copy from: https://docs.google.com/document/d/19J8In7yXjVMQPCNsysOrMUZcK1h6n60V37eOJP-xMWE/pub

Read only link to this document: https://www.overleaf.com/read/mjgdrjvhwjgc
