### ISSUE TITLE
[20] Add a legend displaying the relation between the visualization and the numeric values

### ISSUE THREAD

**Issue by rkeulemans** [vandenheuvel/tribler#211]
As a user I want to see a legend:

- [x] Node radius mapped to the total amount of transmitted data by this node. #222
- [x] Node color mapped to the page rank reputation. #223 
- [x] Edge stroke width mapped to the minimum and maximum transmitted data over a link. #224 
- [x] The legend updates when the graph is updated (i.e. when a new focus node is clicked or when it auto refreshes). #225 

This legend is also a small 'summary' of the part of the network which is currently visible in your display.

See http://d3-legend.susielu.com/

**Comment by rkeulemans** [comment]
@TimSpeelman @vandenheuvel I am considering using http://d3-legend.susielu.com/ for creating the legend. This already implements most (if not all) logic for creating the legend. But it introduces a new dependency. How do you think about this?
