### ISSUE TITLE
[13] 'Back To Me' button

### ISSUE THREAD

**Issue by TimSpeelman** [vandenheuvel/tribler#219]
As a user, when browsing a network, I want to be able to navigate back to my own focus node with a single click.

- [x] Add 'locate me' button #257 
- [x] Remember the taken path from current focus node back to user node #255 
- [x] Animate step-by-step transition from current focus node to user node #259 

The user can navigate through an entire network and reach a focus node far away from his or her own node. This way the user can very easily get lost. As there is no way to reset the view other than to restart Tribler, this button is necessary for usabilty.
