### ISSUE TITLE
[100] Architecture design

### ISSUE THREAD

**Issue by rkeulemans** [vandenheuvel/tribler#22]
"Note that this document needs to be updated during the various sprints to present the current state of the design. The initial version can contain sketches/ideas of the architecture design; the document is then continuously extended throughout the sprints. An example document will be posted on Blackboard. The final document will be at most 10 pages in size.

- [x] #34 Introduction - 4
    - Design goals
- Software architecture views
    - [x] #35 Subsystem decomposition (sub-systems and dependencies between them) - 6
    - [x] #36 Persistent data management (file/ database, database design) - 4
    - [x] #37 Concurrency (processes, shared resources, communication between processes, deadlocks prevention) - 5
- [x] #34 Glossary - 1"
- [x] #55 Updating for week 2
- [x] #56 Updating for week 3
- [x] #57 Updating for week 4
- [x] #58 Updating for week 5
- [x] #59 Updating for week 6
- [x] #60 Updating for week 7
- [x] #61 Updating for week 8
- [x] #62 Readying for hand in

This is a copy from: https://docs.google.com/document/d/19J8In7yXjVMQPCNsysOrMUZcK1h6n60V37eOJP-xMWE/pub

**Comment by vandenheuvel** [comment]
This is now WIP. See [the document on overleaf](https://www.overleaf.com/read/wtzxkvfqvrzq).

**Comment by vandenheuvel** [comment]
@rkeulemans I removed the bullet on hard-ware mapping as it is not relevant to our project.
