### ISSUE TITLE
[30] Make sure not too many nodes are shown on screen

### ISSUE THREAD

**Issue by yinghaodai** [vandenheuvel/tribler#236]
As a user, when I open my trust display, I do not want a screen full of nodes in which I can impossibly find my way.

- [x] Decide upon a good way to filter out nodes (e.g. node groups) (#242)
- [x] Pass on correct information in endpoint (#245)
- [x] Show remaining nodes on trust display (#246)
