### ISSUE TITLE
[13] Node and Link Inspector

### ISSUE THREAD

**Issue by TimSpeelman** [vandenheuvel/tribler#251]
As a user I want to be able to inspect all nodes and edges I see in the view, including al the relevant details so I understand who did what and how reputations came to be.

- [x] Design and implement an inspector 'widget'. #267 
- [x] Fill inspector with node and link data when hovering nodes and links. #264 #265 
- [x] Show network-wide data when no nodes or links are hovered. #268 

In order to truly understand what is displayed in the visualization, a user must be able to find revelant metrics. These metrics tell the user how healthy a node is, and what causes its reputation. This way we intend to convince users of the need to contribute (upload) to the network.
