### ISSUE TITLE
[20] Adjust visualisation to new Tribler version

### ISSUE THREAD

**Issue by ghabbenjansen** [vandenheuvel/tribler#288]
As a user, I want the visualisation to be compatible with the newest version of Tribler

- [x] Change database connection to be compatible (#287)
- [x] Change community to be compatible (#289)
- [x] Change REST API to be compatible (#290)
- [x] Change GUI to be compatible (#291)
