### ISSUE TITLE
[100] Usability of Trust display

### ISSUE THREAD

**Issue by MaxVanDeursen** [vandenheuvel/tribler#4]
The primary goal of the visualization is to teach the user how the Tribler trust mechanism works.

- [x] Create a trust display
- [x] https://github.com/vandenheuvel/tribler/issues/260 Perform user testing to verify whether users understand the display
- [x] https://github.com/vandenheuvel/tribler/issues/262 Process feedback from user testing
- [x] https://github.com/vandenheuvel/tribler/issues/261 Second round of user testing
- [x] https://github.com/vandenheuvel/tribler/issues/263 Process feedback once more
