### ISSUE TITLE
[13] Using the HTTP API to transfer trust information to the GUI

### ISSUE THREAD

**Issue by vandenheuvel** [vandenheuvel/tribler#41]
The HTTP API is used to transfer information gathered and calculated in the core to the GUI.

- [x] https://github.com/vandenheuvel/tribler/issues/42 Creating an API endpoint in the daemon which uses methods from the core
- [ ] https://github.com/vandenheuvel/tribler/issues/43 Making a correct request in the GUI
- [ ] https://github.com/vandenheuvel/tribler/issues/44 Making the results in the GUI readily available to visualization code
